[package]
name = "jg"
version = "0.1.0"
authors = ["Prunoideae <a455167189@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
serde_json = "1.0.61"
regex = "1.4.3"
rayon = "1.5.0"
lazy_static = "1.4.0"
